
version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  web-frontend:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    ports:
      - "80:80"

  mobile-frontend:
    build:
      context: ./frontend/mobile
      dockerfile: Dockerfile
    ports:
      - "81:80"
