services:
  backend:
    build: ./backend
    container_name: zaltixschool-backend
    ports:
      - "5000:5000"

  eshcul:
    build: ./Eshcul
    container_name: zaltixschool-eshcul
    ports:
      - "8081:80"

  web:
    build: ./sphere-entry-animated-home-main
    container_name: zaltixschool-sphere
    ports:
      - "8083:80"

