apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-deployment
  labels:
    app: mobile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile
  template:
    metadata:
      labels:
        app: mobile
    spec:
      containers:
        - name: mobile
          image: rateshivakumar/zaltix-mobile:latest   # ✅ your Docker Hub image
          ports:
            - containerPort: 80   # Nginx inside container
---
apiVersion: v1
kind: Service
metadata:
  name: mobile-service
  labels:
    app: mobile
spec:
  selector:
    app: mobile
  ports:
    - protocol: TCP
      port: 8081        # external service port (like docker-compose)
      targetPort: 80    # maps to container port
  type: NodePort

